#ifndef ELINEEDITINTERFACE_GLOBAL_H
#define ELINEEDITINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELINEEDITINTERFACE_LIBRARY)
#  define ELINEEDITINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define ELINEEDITINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // ELINEEDITINTERFACE_GLOBAL_H
